CREATE DATABASE IF NOT EXISTS keychoose;

USE keychoose;

CREATE TABLE ATTRIBUTE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(42),
    layout VARCHAR(42),
    size VARCHAR(42),
    switch VARCHAR(42),
    connectivity VARCHAR(42),
    rgb VARCHAR(42),
    material VARCHAR(42),
    price VARCHAR(42),
    id_2 VARCHAR(42) NOT NULL,
    id_3 VARCHAR(42) NOT NULL
);

CREATE TABLE CLAVIER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image VARCHAR(42),
    nom VARCHAR(42),
    url VARCHAR(42),
    attribute_Id VARCHAR(42),
    year VARCHAR(42),
    brand VARCHAR(42),
    created VARCHAR(42)
);

CREATE TABLE HISTORIQUE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event VARCHAR(42),
    description VARCHAR(42),
    created VARCHAR(42)
);

CREATE TABLE POSSEDER (
    PRIMARY KEY (id_1, id_2),
    id_1 VARCHAR(42) NOT NULL,
    id_2 VARCHAR(42) NOT NULL
);

CREATE TABLE PROFILE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    attribute_Id VARCHAR(42),
    created VARCHAR(42)
);

CREATE TABLE ROLE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role VARCHAR(42),
    created VARCHAR(42),
    id_2 VARCHAR(42) NOT NULL
);

CREATE TABLE UTILISATEUR (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(42),
    password VARCHAR(42),
    role_Id VARCHAR(42),
    created VARCHAR(42)
);

ALTER TABLE ATTRIBUTE ADD FOREIGN KEY (id_3) REFERENCES CLAVIER (id);
ALTER TABLE ATTRIBUTE ADD FOREIGN KEY (id_2) REFERENCES PROFILE (id);
ALTER TABLE POSSEDER ADD FOREIGN KEY (id_2) REFERENCES PROFILE (id);
ALTER TABLE POSSEDER ADD FOREIGN KEY (id_1) REFERENCES UTILISATEUR (id);
ALTER TABLE ROLE ADD FOREIGN KEY (id_2) REFERENCES UTILISATEUR (id);