CREATE DATABASE IF NOT EXISTS keychoose
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE keychoose;

CREATE TABLE IF NOT EXISTS ROLE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(42) NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UTILISATEUR (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role_id INT,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES ROLE(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ATTRIBUTE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(10),
  layout VARCHAR(10),
  size INT(3),
  `switch` VARCHAR(50) DEFAULT NULL,
  connectivity VARCHAR(30) DEFAULT NULL,
  rgb TINYINT(1) DEFAULT 0,
  material VARCHAR(20),
  price DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS CLAVIER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  image VARCHAR(255),
  nom VARCHAR(255),
  url VARCHAR(255),
  attribute_id INT,
  year VARCHAR(42),
  brand VARCHAR(255),
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (attribute_id) REFERENCES ATTRIBUTE(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PROFILE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  attribute_id INT NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES UTILISATEUR(id) ON DELETE CASCADE,
  FOREIGN KEY (attribute_id) REFERENCES ATTRIBUTE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS POSSEDER (
  user_id INT NOT NULL,
  profile_id INT NOT NULL,
  PRIMARY KEY (user_id, profile_id),
  FOREIGN KEY (user_id) REFERENCES UTILISATEUR(id) ON DELETE CASCADE,
  FOREIGN KEY (profile_id) REFERENCES PROFILE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HISTORIQUE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event VARCHAR(255),
  description TEXT,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS RESET_TOKENS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  token VARCHAR(64) NOT NULL UNIQUE,
  expires DATETIME NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES UTILISATEUR(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LOGS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  action VARCHAR(255) NOT NULL,
  details TEXT,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES UTILISATEUR(id) ON DELETE SET NULL
);

INSERT INTO ROLE (id, role) VALUES (1, 'user'), (2, 'admin') ON DUPLICATE KEY UPDATE role = VALUES(role);