CREATE DATABASE IF NOT EXISTS keychoose
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE keychoose;

CREATE TABLE IF NOT EXISTS ATTRIBUTE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(42),
  layout VARCHAR(42),
  size VARCHAR(42),
  `switch` VARCHAR(42),
  connectivity VARCHAR(42),
  rgb VARCHAR(42),
  material VARCHAR(42),
  price VARCHAR(42),
  id_2 INT NOT NULL,
  id_3 INT NOT NULL
);

CREATE TABLE IF NOT EXISTS CLAVIER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  image VARCHAR(255),
  nom VARCHAR(255),
  url VARCHAR(255),
  attribute_Id INT,
  year VARCHAR(42),
  brand VARCHAR(255),
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS HISTORIQUE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event VARCHAR(255),
  description TEXT,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PROFILE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  attribute_Id INT,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UTILISATEUR (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role_Id INT,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ROLE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(42),
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS POSSEDER (
  id_1 INT NOT NULL,
  id_2 INT NOT NULL,
  PRIMARY KEY (id_1, id_2)
);

CREATE TABLE IF NOT EXISTS RESET_TOKENS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  token VARCHAR(64) NOT NULL UNIQUE,
  expires DATETIME NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES UTILISATEUR(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LOGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    action VARCHAR(255) NOT NULL,
    details TEXT,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES UTILISATEUR(id) ON DELETE SET NULL
);

ALTER TABLE ATTRIBUTE
  ADD FOREIGN KEY (id_3) REFERENCES CLAVIER(id) ON DELETE SET NULL,
  ADD FOREIGN KEY (id_2) REFERENCES PROFILE(id) ON DELETE SET NULL;

ALTER TABLE CLAVIER
  ADD FOREIGN KEY (attribute_Id) REFERENCES ATTRIBUTE(id) ON DELETE SET NULL;

ALTER TABLE PROFILE
  ADD FOREIGN KEY (attribute_Id) REFERENCES ATTRIBUTE(id) ON DELETE SET NULL;

ALTER TABLE UTILISATEUR
  ADD FOREIGN KEY (role_Id) REFERENCES ROLE(id) ON DELETE SET NULL;

ALTER TABLE ROLE
  ADD FOREIGN KEY (id_2) REFERENCES UTILISATEUR(id) ON DELETE CASCADE;

ALTER TABLE POSSEDER
  ADD FOREIGN KEY (id_1) REFERENCES UTILISATEUR(id) ON DELETE CASCADE,
  ADD FOREIGN KEY (id_2) REFERENCES PROFILE(id) ON DELETE CASCADE;

INSERT INTO ROLE (id, role) VALUES (1, 'user'), (2, 'admin');